# Generated by Django 2.1.5 on 2020-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('net', models.CharField(max_length=40)),
                ('talk', models.CharField(max_length=40)),
                ('vald', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('net', models.CharField(max_length=40)),
                ('vald', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talktime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('talk', models.CharField(max_length=40)),
                ('vald', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
