# Generated by Django 2.1.5 on 2020-05-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
